name: build_and_push

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: lint
        # Run ./gradlew spotlessApply when failing on this step.
        run: ./gradlew spotlessCheck --stacktrace
      - name: test
        run: ./gradlew test
